### ISSUE TITLE
long read processing fails

### ISSUE THREAD

**Issue by uloeber** [hildebra/lotus2#18] opened 2021-06-07 11:02 UTC
Dear lotus2 team,
after you uploaded v 2.07 with the long read fix I guess, I tried to process some pacbio data using cd-hit for clustering
```
perl ~/lotus2/lotus2 -i ./ -m lotus2_cleaned.map -s ~/lotus2/configs/sdm_PacBio.txt -o lotus2_SLV138/ -threads 30 -refDB SLV -CL 
```
and unfortunately get the following error:
```
   685605  finished     108831  clusters

Apprixmated maximum memory consumption: 1896M
writing new database
writing clustering information
program completed !

Total CPU time 40411.72

This is sdm (simple demultiplexer) 1.85 beta.

sdm run in No Map Mode.
Could not open uc file
lotus2_SLV138//tmpFiles//finalOTU.uc

```
Do you have any suggestions what might have caused this issue?
Best,
Ulrike

p.s. minor typos in the log: Apprixmated; remove space after completed :)

**Comment by uloeber** [comment] 2021-06-07 11:03
p.p.s. autoinstall runs very smoothly now! thanks a bunch

**Comment by hildebra** [comment] 2021-06-07 12:59
Hey Ulrike,

Please note that the long read fix concerned a particular problem, it's not the final PacBio version, this is still in alpha.
The error you report could be a warning, hard to see where the pipeline breaks. Can you send the whole lotus_logs dir to me (zipped)?

The typos are not from LotuS, but from CD-HIT as far as I can see. 

cheers, Falk

**Comment by uloeber** [comment] 2021-06-07 13:10
Hey Falk,
thanks for looking into it! I uploaded the compressed error log to [Dropbox](https://www.dropbox.com/s/lrd0clh4s92cm1v/LotuSLogS_pacbio_UL.tar?dl=0).
Cheers,
Ulrike

**Comment by hildebra** [comment] 2021-06-07 14:10
Looking through the logs, yes a bit weird. So first off, I note that you have an extremely high unique sequence fraction, and that you deactivated derep. Not a problem per se, just noteable. So a very rich community.
Second, seems to be indeed a hard error for sdm not finding a file, does this file exist (and what size)?
lotus2_SLV138//tmpFiles//finalOTU.uc
If it doesn't exist, can you run this command and see if the file gets then created?
"/home/uloeber/lotus2//bin//vsearch-2.0.4 --usearch_global lotus2_SLV138//tmpFiles//derep.fas -db lotus2_SLV138//tmpFiles//tmp_otu.fa -uc lotus2_SLV138//tmpFiles//finalOTU.uc --maxhits 1 --query_cov 0.8 --maxrejects 200 -top_hits_only -strand both -id 0.97 -threads 30  --dbmask none --qmask none"

**Comment by uloeber** [comment] 2021-06-09 13:02
No errors here:
```
/home/uloeber/lotus2//bin//vsearch-2.0.4 --usearch_global lotus2_SLV138//tmpFiles//derep.fas -db lotus2_SLV138//tmpFiles//tmp_otu.fa -uc lotus2_SLV138//tmpFiles//finalOTU.uc --maxhits 1 --query_cov 0.8 --maxrejects 200 -top_hits_only -strand both -id 0.97 -threads 30 --dbmask none --qmask none
(base) [uloeber@sl-sci-forsl1 Aquavir]$ vsearch --usearch_global lotus2_SLV138/tmpFiles/derep.fas -db lotus2_SLV138/tmpFiles/tmp_otu.fa -uc lotus2_SLV138/tmpFiles/finalOTU.uc --maxhits 1 --query_cov 0.8 --maxrejects 200 -top_hits_only -strand both -id 0.97 -threads 30 --dbmask none --qmask none
vsearch v2.14.2_linux_x86_64, 70.6GB RAM, 40 cores
https://github.com/torognes/vsearch

Reading file lotus2_SLV138/tmpFiles/tmp_otu.fa 100%
160213806 nt in 108831 seqs, min 997, max 1500, avg 1472
Counting k-mers 100%
Creating k-mer index 100%
Searching 100%
Matching unique query sequences: 680222 of 685605 (99.21%)
```

**Comment by hildebra** [comment] 2021-06-10 07:27
that's good, but did the file "lotus2_SLV138//tmpFiles//finalOTU.uc" exist already before you ran this command? can you check if the sdm call works now? Is this actually the dataset you send me ~6 months ago, then it might be faster if I try to reproduce it

**Comment by uloeber** [comment] 2021-06-10 12:32
yes, should be the same dataset.  Seems like the file has not been created before.

**Comment by hildebra** [comment] 2021-06-10 13:25
ok, then I guess it's an OOM, can you check that the process has enough RAM and run lotus2 again?

**Comment by uloeber** [comment] 2021-06-10 13:34
Okay, I will. used 60GB of RAM, but now heading for 300GB

**Comment by hildebra** [comment] 2021-06-10 13:47
Ulrike, we just checked, and it seems that there's a problem with autoinstall installing vsearch wrong. We'll look deeper into this, for now, can you edit the lOTUs.cfg, look for vsearch and check that this file really exists ( and is excecutable, so shows a help when run)?

**Comment by uloeber** [comment] 2021-06-10 13:58
AH, yes this could be the case, I remember that this time I was not asked to give search path.

**Comment by hildebra** [comment] 2021-06-11 16:19
Ulrike, I just pushed an update that should fix the autoInstall not associating the right vsearch. If you could give it a try (git pull) and check whether in lOTUs.cfg the vsearch is correctly set (and the set file really exists and is excecuting)? Thanks

**Comment by uloeber** [comment] 2021-06-14 12:50
looks like it works now, but hanging at the next step:
```
[cmd] /home/uloeber/lotus2//bin//vsearch-2.0.4 --usearch_global lotus2_SLV138//tmpFiles//derep.fas -db lotus2_SLV138//tmpFiles//tmp_otu.fa -uc lotus2_SLV138//tmpFiles//finalOTU.uc --maxhits 1 --query_cov 0.8 --maxrejects 200 -top_hits_only -strand both -id 0.97 -threads 30  --dbmask none --qmask none
[cmd] /home/uloeber/lotus2//bin//sdm -i_fastq lotus2_SLV138//tmpFiles//derep.1.hq.fq -o_fna lotus2_SLV138//tmpFiles//otu_seeds.fna  -optimalRead2Cluster lotus2_SLV138//tmpFiles//finalOTU.uc -paired 1 -sample_sep ___ -derep_map lotus2_SLV138//tmpFiles//derep.map -options /home/uloeber/lotus2/configs/sdm_PacBio.txt -merge_pairs_seed 1  -o_qual_offset 33 -mergedPairs 0 -log lotus2_SLV138//LotuSLogS//SeedExtensionStats.txt  -OTU_fallback lotus2_SLV138//tmpFiles//tmp_otu.fa -ucAdditionalCounts lotus2_SLV138//tmpFiles//finalOTU.uc.ADD -ucAdditionalCounts1 lotus2_SLV138//tmpFiles//finalOTU.uc.REST -otu_matrix lotus2_SLV138//OTU.txt -count_chimeras F 

```
btw, running lotus2 with defaults on miseq data gives: 
`CMD failed: /usr/local/bin/vsearch -cluster_otus lotus2_SLV138//tmpFiles//derep.fas -otus lotus2_SLV138//tmpFiles//tmp_otu.fa   -log lotus2_SLV138//LotuSLogS//UPARSE.log  -uparseout lotus2_SLV138//tmpFiles//finalOTU.uc  `
`/usr/local/bin/vsearch: unrecognized option '-cluster_otus'
` using vesarch 2.14.2 any idea?

**Comment by hildebra** [comment] 2021-06-14 17:00
What is the error you get at the step? Just from the command I can't see where the problem is.

About miseq: yes vsearch doesn't support cluster_otus.. Thanks, I'll remove this combination. I guess you have not installed usearch (only usearch can do this clustering step)?

**Comment by uloeber** [comment] 2021-06-16 09:39
Hi Falk,
yes thats true. Its my bad. I assigned search to search in the config.
Cheers,
Ulrike

**Comment by hildebra** [comment] 2021-06-16 09:51
Ok no problem, I'll close the issue then.

**Closed by hildebra** 2021-06-16 09:51 UTC

**Comment by hildebra** [comment] 2021-06-16 09:54
PS: there's the hidden argument "./lotus2 -useVsearch 0". if you put this on 1, lotus2 will try to use vsearch where possible, this can be helpful in case your data is too big and usearch complains about out of mem etc
